import { Response } from 'express';
import { PrismaClient } from '@prisma/client';
import { AuthRequest } from '../middlewares/auth.middleware';
import { GoogleGenerativeAI } from '@google/generative-ai';

const prisma = new PrismaClient();

const genAI = new GoogleGenerativeAI(process.env.GEMINI_API_KEY || '');

export const generateBio = async (req: AuthRequest, res: Response): Promise<void> => {
  try {
    const { memberId, bulletPoints } = req.body;
    
    if (!process.env.GEMINI_API_KEY || process.env.GEMINI_API_KEY === 'YOUR_GEMINI_API_KEY_HERE') {
      res.status(500).json({ error: 'GEMINI_API_KEY is not configured on the server. Please add a valid API key to the .env file.' });
      return;
    }

    if (!memberId || !bulletPoints || !Array.isArray(bulletPoints)) {
      res.status(400).json({ error: 'Invalid input. Required: memberId, bulletPoints[]' });
      return;
    }

    // Fetch member details for context
    const member = await prisma.member.findUnique({
      where: { id: memberId },
      include: {
        tree: {
          select: { name: true }
        }
      }
    });

    if (!member) {
      res.status(404).json({ error: 'Member not found' });
      return;
    }

    // Prepare context for Gemini
    const context = `
      Name: ${member.name}
      Birth Date: ${member.birthDate ? new Date(member.birthDate).toDateString() : 'Unknown'}
      Birth Location: ${member.birthLocation || 'Unknown'}
      Gender: ${member.gender || 'Unknown'}
      Status: ${member.deathDate ? `Deceased (Died: ${new Date(member.deathDate).toDateString()})` : 'Living'}
      Family Tree: ${member.tree.name}
    `;

    const prompt = `
      You are an expert Indian family historian and professional biographer. 
      Write a beautiful, culturally-aware, and engaging 2-paragraph biography for the following person.
      
      Here is the raw database context about them:
      ${context}

      Here are specific life events and facts provided by the family:
      ${bulletPoints.map(bp => `- ${bp}`).join('\n')}
      
      Requirements:
      1. Write in a warm, respectful, and engaging tone suitable for a family tree.
      2. Naturally weave the provided life events and raw context together into a cohesive narrative.
      3. Do not mention that this was generated by an AI.
      4. Do not invent major life facts that are not provided in the bullet points or context, but you may add mild stylistic flourish.
      5. Output ONLY the biography text.
    `;

    const model = genAI.getGenerativeModel({ model: "gemini-1.5-flash" });
    const result = await model.generateContent(prompt);
    const response = await result.response;
    const text = response.text();

    res.status(200).json({ bio: text.trim() });
  } catch (error) {
    console.error('AI Bio Generation error:', error);
    res.status(500).json({ error: 'Failed to generate bio' });
  }
};
